server.port=8080
spring.jackson.date-format=com.cgi.eoss.ogcapi.processes.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
#Actuator Endpoints
management.server.port=8081
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true